# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-05 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_article_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(default='abstract', verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_post.Category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_post.Article', verbose_name='评论所属文章'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='body',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论发表时间'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user_email',
            field=models.EmailField(max_length=255, verbose_name='评论者邮箱'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user_name',
            field=models.CharField(max_length=100, verbose_name='评论者名字'),
        ),
        migrations.AlterField(
            model_name='category',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, verbose_name='类名'),
        ),
    ]
